name: LisaCook
favicon: null
layout_spectrum: 0.912732430966571
typography_spectrum: 0.4303382511716336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.07160428143106401
  lightness: 0.9625230797100812
  saturation: 0.05976107367314398
  rhythmicContrast: 0.6189385729376227
purpose: []
