name: LisaCook
favicon: null
layout_spectrum: 0.96176
typography_spectrum: 0.13279
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d6d8'
    - '#b42b45'
    - '#243700'
    - '#060501'
    - '#52790c'
  brandStrength: 0.5
  lightness: 0.9625230797100812
  saturation: 0.125
  rhythmicContrast: 0.6189385729376227
purpose: []
